"""added added_by field

Revision ID: 870e5414e2ec
Revises: 
Create Date: 2022-10-28 11:42:19.890976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870e5414e2ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinion', 'added_by')
    # ### end Alembic commands ###
